/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Meetings
         * @description Meetings whose agenda items or text match the query. Snippets mark matches with \x02…\x03.
         */
        get: operations["search_meetings_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meetings */
        get: operations["meetings_api_meetings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting */
        get: operations["meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List People
         * @description People who attended at least one meeting. q matches any spelling of the name.
         */
        get: operations["list_people_api_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Person */
        get: operations["person_api_people__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board Years
         * @description The years with board meetings, oldest first.
         */
        get: operations["board_years_api_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description The board of a year, inferred from the attendance of that term's board meetings.
         */
        get: operations["board_api_boards__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document File
         * @description The original document, shown inline by the browser when it can (PDF).
         */
        get: operations["document_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendeeView */
        AttendeeView: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Role */
            role: string | null;
            /** Person Id */
            person_id: number;
            /** Person Name */
            person_name: string;
        };
        /** Board */
        Board: {
            /** Year */
            year: number;
            /** Meetings */
            meetings: components["schemas"]["BoardMeeting"][];
            /** Members */
            members: components["schemas"]["BoardMember"][];
            /** Others */
            others: components["schemas"]["BoardMember"][];
        };
        /** BoardMeeting */
        BoardMeeting: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Meeting Date */
            meeting_date: string | null;
            /** Meeting Number */
            meeting_number: string | null;
        };
        /** BoardMember */
        BoardMember: {
            /** Person Id */
            person_id: number;
            /** Name */
            name: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Present */
            present: number;
            /** Absent */
            absent: number;
        };
        /** BoardTerm */
        BoardTerm: {
            /** Year */
            year: number;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Present */
            present: number;
            /** Absent */
            absent: number;
            /** Meetings */
            meetings: number;
        };
        /** BoardYear */
        BoardYear: {
            /** Year */
            year: number;
            /** Meetings */
            meetings: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingHit */
        MeetingHit: {
            /** Meeting Id */
            meeting_id: number;
            /** Title */
            title: string;
            /**
             * Meeting Type
             * @enum {string}
             */
            meeting_type: "board" | "spring_general" | "autumn_general" | "extraordinary" | "other";
            /** Meeting Date */
            meeting_date: string | null;
            /** Document Id */
            document_id: number;
            /** File Type */
            file_type: string;
            /** Score */
            score: number;
            /** Topics */
            topics?: components["schemas"]["TopicHit"][];
            /** Text */
            text?: components["schemas"]["TextHit"][];
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Type
             * @enum {string}
             */
            meeting_type: "board" | "spring_general" | "autumn_general" | "extraordinary" | "other";
            /** Meeting Number */
            meeting_number: string | null;
            /** Term Year */
            term_year: number | null;
            /** Meeting Date */
            meeting_date: string | null;
            /** Location */
            location: string | null;
            /** Topic Count */
            topic_count: number;
            /** Decision Count */
            decision_count: number;
            /** Document Id */
            document_id: number;
            /** File Type */
            file_type: string;
        };
        /** MeetingView */
        MeetingView: {
            /** Title */
            title: string;
            /**
             * Meeting Type
             * @enum {string}
             */
            meeting_type: "board" | "spring_general" | "autumn_general" | "extraordinary" | "other";
            /** Meeting Number */
            meeting_number: string | null;
            /** Term Year */
            term_year: number | null;
            /** Meeting Date */
            meeting_date: string | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Location */
            location: string | null;
            /** Summary */
            summary: string | null;
            /** Warnings */
            warnings: string[];
            /** Attendees */
            attendees: components["schemas"]["AttendeeView"][];
            /** Topics */
            topics: components["schemas"]["TopicView"][];
            /** Id */
            id: number;
            /** Document Id */
            document_id: number;
            /** Rel Path */
            rel_path: string;
            /** File Type */
            file_type: string;
            /** Page Count */
            page_count: number | null;
        };
        /** PersonMeeting */
        PersonMeeting: {
            /** Meeting Id */
            meeting_id: number;
            /** Title */
            title: string;
            /**
             * Meeting Type
             * @enum {string}
             */
            meeting_type: "board" | "spring_general" | "autumn_general" | "extraordinary" | "other";
            /** Meeting Date */
            meeting_date: string | null;
            /** Status */
            status: string;
            /** Role */
            role: string | null;
            /** Name As Written */
            name_as_written: string;
        };
        /** PersonResponse */
        PersonResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Spellings */
            spellings: string[];
            /** Meetings */
            meetings: components["schemas"]["PersonMeeting"][];
            /** Board Terms */
            board_terms: components["schemas"]["BoardTerm"][];
        };
        /** PersonSummary */
        PersonSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Meetings */
            meetings: number;
            /** First Year */
            first_year: number | null;
            /** Last Year */
            last_year: number | null;
            /** Spellings */
            spellings: string[];
            /** Board Years */
            board_years: number[];
        };
        /** Role */
        Role: {
            /** Name */
            name: string;
            /** Meetings */
            meetings: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["MeetingHit"][];
        };
        /** TextHit */
        TextHit: {
            /** Page No */
            page_no: number | null;
            /** Snippet */
            snippet: string;
        };
        /** TopicHit */
        TopicHit: {
            /** Id */
            id: number;
            /** Item Number */
            item_number: string | null;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Page No */
            page_no: number | null;
            /** Has Decision */
            has_decision: boolean;
        };
        /** TopicView */
        TopicView: {
            /** Item Number */
            item_number: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Decisions */
            decisions: string | null;
            /** Page No */
            page_no: number | null;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    search_meetings_api_search_get: {
        parameters: {
            query: {
                q: string;
                year_from?: number | null;
                year_to?: number | null;
                type?: ("board" | "spring_general" | "autumn_general" | "extraordinary" | "other") | null;
                sort?: "relevance" | "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meetings_api_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingSummary"][];
                };
            };
        };
    };
    meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_api_people_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    person_api_people__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_years_api_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardYear"][];
                };
            };
        };
    };
    board_api_boards__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
