/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Meetings
         * @description Meetings whose agenda items or text match the query. Snippets mark matches with \x02…\x03.
         */
        get: operations["search_meetings_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meetings */
        get: operations["meetings_api_meetings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting */
        get: operations["meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document File
         * @description The original document, shown inline by the browser when it can (PDF).
         */
        get: operations["document_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendeeView */
        AttendeeView: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Role */
            role: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingHit */
        MeetingHit: {
            /** Meeting Id */
            meeting_id: number;
            /** Title */
            title: string;
            /** Meeting Type */
            meeting_type: string;
            /** Meeting Date */
            meeting_date: string | null;
            /** Document Id */
            document_id: number;
            /** File Type */
            file_type: string;
            /** Score */
            score: number;
            /** Topics */
            topics?: components["schemas"]["TopicHit"][];
            /** Text */
            text?: components["schemas"]["TextHit"][];
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Meeting Type */
            meeting_type: string;
            /** Meeting Date */
            meeting_date: string | null;
            /** Location */
            location: string | null;
            /** Topic Count */
            topic_count: number;
            /** Decision Count */
            decision_count: number;
            /** Document Id */
            document_id: number;
            /** File Type */
            file_type: string;
        };
        /** MeetingView */
        MeetingView: {
            /** Title */
            title: string;
            /** Meeting Type */
            meeting_type: string;
            /** Meeting Date */
            meeting_date: string | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Location */
            location: string | null;
            /** Summary */
            summary: string | null;
            /** Warnings */
            warnings: string[];
            /** Attendees */
            attendees: components["schemas"]["AttendeeView"][];
            /** Topics */
            topics: components["schemas"]["TopicView"][];
            /** Id */
            id?: number | null;
            /** Document Id */
            document_id?: number | null;
            /** Rel Path */
            rel_path?: string | null;
            /** File Type */
            file_type?: string | null;
            /** Page Count */
            page_count?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["MeetingHit"][];
        };
        /** TextHit */
        TextHit: {
            /** Page No */
            page_no: number | null;
            /** Snippet */
            snippet: string;
        };
        /** TopicHit */
        TopicHit: {
            /** Id */
            id: number;
            /** Item Number */
            item_number: string | null;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Page No */
            page_no: number | null;
            /** Has Decision */
            has_decision: boolean;
        };
        /** TopicView */
        TopicView: {
            /** Item Number */
            item_number: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Decisions */
            decisions: string | null;
            /** Page No */
            page_no: number | null;
            /** Id */
            id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    search_meetings_api_search_get: {
        parameters: {
            query: {
                q: string;
                year_from?: number | null;
                year_to?: number | null;
                type?: ("board" | "spring_general" | "autumn_general" | "extraordinary" | "other") | null;
                sort?: "relevance" | "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meetings_api_meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingSummary"][];
                };
            };
        };
    };
    meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
